---
title: "404 Homework 3"
author: "Paul Beeman"
date: "February 12, 2018"
output: word_document
---
#Plot 1
#Plot 2
#Part1
##C Code Part 1



##R Code Part 1
```{r}
setwd("~/C")
library(ggplot2)
dyn.load("alt2.dll")
estimate_vector <- double(1000000)
ln_2_est <- .C("alt2", as.integer(1000000), double(1000000))

#I just picked an arbitrary number for the length.out argument for x and y so they are equal
plot(x=seq(0,10000000,length.out = 10),y= seq(.691,.695,length.out = 10), type="n", xlab= "Series Length", ylab = "Ln(2) Estimate")
points(ln_2_est[[2]], pch = ".")
abline(log(2), 0, col="red")

#ggplot alternative
ln2_data <- as.data.frame(ln_2_est[[2]])
ln2_data <- as.data.frame(cbind(c(100:100000),ln2_data[c(100:100000),]))
ln2_plot <- ggplot(data = ln2_data, aes(ln2_data[,1], ln2_data[,2]))
ln2_plot + geom_point(color= "salmon") +geom_abline(slope = 0, intercept = log(2), color = "lemonchiffon") + xlab("Series Length") + ylab("Ln(2) Approximation") + ggtitle("Series Approximation of Ln(2)") + theme_dark()+ theme(plot.title = element_text(hjust = 0.5, size = 18))


```

#Part 2
##C Code

##R Code

```{r data entry}

Earthquakes_3 <- read.table("C:/Users/paulb/Downloads/SearchResults.txt", skip = 2, nrows = 2471)
Earthquake_headers <- c("YYYY/MM/DD", "HH:mm:SS.ss", "ET", "GT", "MAG", "M","LAT","LON","DEPTH", "Q",  "EVID", "NPH", "NGRM")
names(Earthquakes_3) <- Earthquake_headers
head(Earthquakes_3)
```

```{r inputs to c function}
#I am going to write these variables in the form description_cFunctionLocation for my own future reference
magnitudes_x <- Earthquakes_3$MAG
grid_g <- seq(min(magnitudes_x), max(magnitudes_x), length.out = 100)
kernalStorage_y <- rep(0,100)
m <- 100
n <- length(magnitudes_x)
bandwidth_b <- bw.nrd(magnitudes_x)
```

```{r C function attempt}
setwd("~/C")
dyn.load("norm_kern.dll")
approx_mag <- .C("norm_kern", as.integer(m), as.integer(n), as.double(bandwidth_b), as.double(grid_g), as.double(magnitudes_x), as.double(kernalStorage_y))
hist(magnitudes_x,nclass = 50, probability = T)
lines(grid_g, approx_mag[[6]], col= "blue")

#ggplot alternative

library(ggplot2)
mag_data <- as.data.frame(magnitudes_x)
kern_data <- as.data.frame(cbind(grid_g,approx_mag[[6]]))
quake_plot <- ggplot()
quake_plot + geom_histogram(data= mag_data, aes(x = magnitudes_x, y=..density..),bins = 30, col = "dark grey", fill = "orange") + 
geom_area(data = kern_data, aes(x=grid_g, y=kern_data$V2), color="black", fill= "yellow", alpha = .4)+ xlab("Magnitudes")+ylab("Density")+ggtitle("SoCal Earthquakes") + 
theme(plot.title = element_text(hjust = 0.5, size = 18), 
axis.title.x = element_text(size = 16),
axis.title.y = element_text(size = 16),
axis.text.y=element_text(size = 14),
axis.text.x=element_text(size = 14))



```









